version: "3.4"

services:
  marleyspoon-task-main-image:
    build: .
    image: marleyspoon-task

  train-model:
    image: marleyspoon-task
    depends_on:
      - marleyspoon-task-main-image
    command: python src/train.py
      --input-train-csv /home/project/data/train_data_cleaned.csv
      --input-test-csv /home/project/data/test_data_cleaned.csv
      --output-model /home/project/models/model.joblib
      --output-test-pred /home/project/data/test_predictions.csv
      --n-val-weeks 8
      --n-cv-folds 4
    volumes:
      - .:/home/project

  notebook:
    image: marleyspoon-task
    depends_on:
      - marleyspoon-task-main-image
    command: jupyter notebook
      --notebook-dir=/home/project/notebooks
      --ip 0.0.0.0
      --no-browser
      --allow-root
      --port 8989
    ports:
      - "8989:8989"
    volumes:
      - .:/home/project
